import type { Lang } from "./i18n";
import imageManifest from "./projects.images.json";
import translations from "./projects.i18n.json";

/* EN/PT/IT translations of each project, keyed by slug. Generated from the
   Spanish source and kept in a separate data file so the copy is easy to
   review and replace. Missing slugs/languages fall back to Spanish. */
const TRANSLATIONS = translations as Record<string, Partial<Record<Lang, ProjectContent>>>;

/* ---------------------------------------------------------------------------
   Project content model.

   One entry per real project. Text lives per-language under `content`; when a
   language is missing the accessor falls back to Spanish (the source language),
   so the site works in all four languages while translations are filled in.

   Images are referenced by convention at /uploads/projects/<slug>/… and degrade
   to the striped placeholder until the real files are dropped in public/.
--------------------------------------------------------------------------- */

export interface ProjectContent {
  /** Short descriptor shown as the card/panel headline — no client name, no
      "Branding/Rebranding" (the client is always shown next to it). e.g.
      "Comunicación sin barreras" */
  title: string;
  /** "Frase descriptiva del proyecto" */
  tagline: string;
  /** Hero phrase */
  heroPhrase: string;
  /** Overview body */
  summary: string;
  /** The challenge */
  challenge: string;
  /** Our approach — one entry per paragraph */
  approach: string[];
  /** The outcome — one entry per paragraph */
  outcome: string[];
  /** "Frases sobre el proyecto" */
  quotes: string[];
  /** Discipline tags, e.g. "Branding · Estrategia" */
  tags: string;
  /** Sector, e.g. "Tecnología" */
  sector: string;
  /** City, when known */
  location?: string;
}

export interface Project {
  slug: string;
  client: string;
  year?: string;
  cover: string;
  /** Animated cover (a .gif) used ONLY on the individual project page's hero.
      The home rail and the archive keep the static `cover` image. */
  coverAnimated?: string;
  gallery: string[];
  video?: string;
  content: Partial<Record<Lang, ProjectContent>>;
}

/* Images per project come from lib/projects.images.json, generated by
   scripts/build-image-manifest.mjs scanning public/uploads/projects/<slug>/.
   Drop files there with any names (see docs/ASSETS.md) — the manifest is
   rebuilt automatically before every build/dev run. Until a project has real
   files it falls back to the by-convention placeholder paths, which degrade to
   the striped placeholder. `cover` is the first image; `gallery` is the rest
   (the detail page uses the first four and shows any extras in a closing grid). */
const MANIFEST = imageManifest as Record<string, { images: string[]; hero?: string }>;

const img = (slug: string) => {
  const entry = MANIFEST[slug];
  const files = entry?.images ?? [];
  const coverAnimated = entry?.hero;
  if (files.length === 0) {
    return {
      cover: `/uploads/projects/${slug}/cover.webp`,
      gallery: [1, 2, 3, 4].map((n) => `/uploads/projects/${slug}/${n}.webp`),
      coverAnimated,
    };
  }
  const cover = files[0];
  const rest = files.length > 1 ? files.slice(1) : files;
  return { cover, gallery: rest, coverAnimated };
};

export const PROJECTS: Project[] = [
  {
    slug: "dillo",
    client: "Dillo",
    ...img("dillo"),
    content: {
      ES: {
        title: "Comunicación sin barreras",
        tagline: "Una identidad que transforma la accesibilidad en una experiencia de marca humana, contemporánea y universal.",
        heroPhrase: "Diseñamos una marca para que todas las personas puedan formar parte de la conversación.",
        summary:
          "Creamos la identidad estratégica y visual de Dillo, una startup que utiliza comunidad y tecnología para facilitar la comunicación entre personas sordas y oyentes. El proyecto convirtió una misión centrada en la inclusión en una marca cercana, reconocible y preparada para crecer en distintos entornos.",
        challenge:
          "Dillo necesitaba construir una marca capaz de abordar un desafío complejo y profundamente humano: reducir las barreras de comunicación entre personas sordas y oyentes. El reto consistía en representar inclusión y accesibilidad sin recurrir a códigos institucionales, asistencialistas o excesivamente tecnológicos. La identidad debía ser clara y confiable, pero también cálida, expresiva y capaz de conectar con personas, profesionales y organizaciones de contextos diversos.",
        approach: [
          "Desarrollamos una estrategia de marca basada en la comunicación como puente entre mundos. Definimos su propósito, visión, valores, propuesta de valor y lenguaje conceptual, integrando inclusión, empatía, innovación y colaboración como principios centrales.",
          "La identidad visual nació de una idea simple: escuchar también es abrir un espacio para comprender. A partir de ese concepto diseñamos un logotipo cuyos paréntesis evocan una oreja atenta y, al mismo tiempo, pueden representar ojos, una boca y una conversación abierta.",
          "Construimos un sistema flexible con una paleta vital y accesible, una combinación tipográfica de carácter contemporáneo, patterns derivados del símbolo e ilustraciones a mano alzada que reflejan diversidad, autenticidad y situaciones reales de comunicación.",
        ],
        outcome: [
          "El resultado fue una identidad integral, humana y versátil, capaz de expresar la misión de Dillo de manera coherente en experiencias digitales, campañas, piezas editoriales y aplicaciones de marca.",
          "Más que representar una solución tecnológica, el sistema posiciona a Dillo como una comunidad abierta: un espacio donde las diferencias no separan, sino que encuentran nuevas formas de conectarse.",
        ],
        quotes: [
          "Convertimos la escucha en el punto de partida de todo el sistema de identidad.",
          "Una marca inclusiva no se limita a hablar de accesibilidad: debe hacer que cada persona se sienta parte.",
          "Dillo nació para transformar la comunicación en un puente, nunca en una barrera.",
        ],
        tags: "Branding · Estrategia",
        sector: "Tecnología",
      },
    },
  },
  {
    slug: "casa-capo",
    client: "Casa Capo",
    ...img("casa-capo"),
    video: "/uploads/projects/casa-capo/colores.mp4",
    content: {
      ES: {
        title: "Una nueva categoría gastronómica",
        tagline: "Una marca que eleva lo cotidiano a través del oficio, la sensibilidad y la obsesión por el detalle.",
        heroPhrase: "Todo está en el primer bocado.",
        summary:
          "Desarrollamos la estrategia y la identidad visual de Casa Capo, una propuesta de entrepanes de autor que transforma el sándwich en una experiencia gastronómica completa. El proyecto construye valor alrededor del producto, el proceso y cada decisión que sucede antes del primer bocado.",
        challenge:
          "Casa Capo necesitaba posicionar una propuesta gastronómica sofisticada sin perder cercanía ni convertirla en una experiencia pretenciosa. El desafío era cambiar la percepción del sándwich como un producto rápido o estandarizado y presentarlo como un plato pensado, capaz de reunir técnica, ingredientes nobles, creatividad y una mirada de autor. La marca debía expresar calidad y conocimiento, pero también honestidad, calidez y accesibilidad: demostrar que una experiencia especial no necesita la formalidad de la alta gastronomía tradicional.",
        approach: [
          "Construimos el universo de Casa Capo alrededor de una idea central: el primer bocado como síntesis de todo el proceso. Ese instante concentra texturas, aromas y sabores, pero también las pruebas, las decisiones, el conocimiento y las manos que hicieron posible el producto.",
          "Definimos una personalidad sensorial, honesta, precisa y profundamente humana, acompañada por un tono de voz sobrio, experto y cercano. La comunicación habla desde el producto y los sentidos, evitando exageraciones, clichés gastronómicos y tecnicismos innecesarios.",
          "La identidad visual se desarrolló como un sistema tipográfico sólido y expresivo. El logotipo transmite presencia y seguridad, mientras que la inclinación de la letra final introduce un gesto propio que representa movimiento, singularidad y autoría. El sistema se completó con composiciones alternativas, un sello de procedencia, una paleta cálida y aplicaciones capaces de funcionar en el espacio, el packaging, la comunicación y el merchandising.",
        ],
        outcome: [
          "El resultado fue una marca gastronómica contemporánea, reconocible y con una categoría propia: entrepán de autor.",
          "Casa Capo logra elevar el producto sin alejarlo de las personas. La identidad hace visible el cuidado que existe detrás de cada preparación y convierte un formato cotidiano en una experiencia con carácter, criterio y valor percibido. Más que vender sándwiches, la marca construye una cultura alrededor del primer bocado.",
        ],
        quotes: [
          "No diseñamos una marca para un sándwich. Diseñamos una identidad para todo lo que sucede antes del primer bocado.",
          "Casa Capo demuestra que la buena gastronomía no depende del formato, sino del cuidado detrás de cada decisión.",
          "Una marca donde el oficio se percibe, la técnica no se impone y el producto dice la verdad.",
        ],
        tags: "Branding · Packaging",
        sector: "Gastronomía",
      },
    },
  },
  {
    slug: "lomo-loco",
    client: "Lomo Loco",
    ...img("lomo-loco"),
    content: {
      ES: {
        title: "Un clásico con espíritu de social club",
        tagline: "Una identidad que renueva un clásico sin perder el sabor, la generosidad ni las historias que lo hicieron parte de la ciudad.",
        heroPhrase: "La sobremesa es nuestro plato más fuerte.",
        summary:
          "Rediseñamos la estrategia y la identidad de Lomo Loco, un restaurante con treinta años de historia en Río Cuarto. El proyecto recupera la esencia del bodegón argentino y la transforma en una marca contemporánea, alegre y profundamente humana, construida alrededor de la comida abundante, el encuentro y la sobremesa.",
        challenge:
          "Lomo Loco contaba con una trayectoria reconocida, una propuesta gastronómica generosa y un fuerte vínculo emocional con su público, pero necesitaba actualizar su identidad para proyectarse hacia una nueva etapa. El desafío era modernizar la marca sin borrar su historia ni convertirla en un restaurante genérico. Debíamos conservar la cercanía, el sabor casero y el espíritu familiar del bodegón, mientras construíamos un sistema más contemporáneo, consistente y reconocible en el espacio, la comunicación digital, el packaging y cada punto de contacto. También era necesario ampliar su posicionamiento: dejar de presentarlo únicamente como un lugar donde se come abundante para mostrarlo como un verdadero punto de encuentro.",
        approach: [
          "Construimos la estrategia alrededor de un territorio propio: la alegría de la sobremesa. Más allá de los platos, Lomo Loco representa las conversaciones que se alargan, las risas compartidas y esa sensación de querer quedarse un rato más.",
          "Redefinimos la personalidad como alegre, generosa, hospitalaria y un poco loca —de las buenas—, con un tono cercano, enfático y afectuoso. La voz de la marca se inspira en una abuela divertida: cocina de más, recibe con cariño y siempre tiene una historia para compartir.",
          "La nueva identidad visual combina códigos de los antiguos bodegones y clubes sociales argentinos con una ejecución contemporánea. Diseñamos un logotipo robusto y modular, múltiples versiones para diferentes formatos, una paleta cálida inspirada en el fuego, el vino y el hogar, y un sistema de ilustraciones que representa mesas compartidas, familias, amigos, cocineros y escenas cotidianas. El descriptor Social Club refuerza el posicionamiento y transforma al restaurante en algo más amplio: un espacio de pertenencia donde comer también significa encontrarse.",
        ],
        outcome: [
          "El resultado fue una identidad renovada que conserva la memoria y el carácter de Lomo Loco, pero los expresa con mayor claridad, energía y coherencia. La marca dejó de depender únicamente de su producto para construir un universo reconocible alrededor de la hospitalidad, la abundancia y el disfrute compartido.",
          "El nuevo sistema puede vivir con consistencia en el restaurante, la fachada, las redes sociales, los menús, la papelería, el packaging y el merchandising. Lomo Loco se consolida así como un bodegón moderno con alma festiva y corazón familiar: un lugar donde la comida reúne y la alegría permanece después del último plato.",
        ],
        quotes: [
          "No rediseñamos solamente un restaurante. Renovamos un lugar que forma parte de la memoria de su ciudad.",
          "Convertimos treinta años de historia en una identidad preparada para las próximas generaciones.",
          "En Lomo Loco, la comida llena el plato; la sobremesa construye la marca.",
        ],
        tags: "Rebranding · Packaging",
        sector: "Gastronomía",
        location: "Río Cuarto",
      },
    },
  },
  {
    slug: "polylepis",
    client: "Polylepis",
    ...img("polylepis"),
    content: {
      ES: {
        title: "Otra dimensión del viaje",
        tagline: "Una identidad que encuentra el equilibrio entre aventura y calma, movimiento y contemplación, partir y volver.",
        heroPhrase: "La dimensión del viaje.",
        summary:
          "Desarrollamos la estrategia y la identidad visual de Polylepis, una marca de viajes y aventura que propone experiencias auténticas, equilibradas y conectadas con la naturaleza, la cultura local y la transformación personal. El proyecto convierte el viaje en algo más profundo que un desplazamiento: un movimiento que permite descubrir, volver y reconocerse.",
        challenge:
          "Polylepis necesitaba diferenciarse dentro de una categoría saturada de paisajes espectaculares, promesas épicas y discursos genéricos sobre aventura. El desafío consistía en construir una marca capaz de transmitir emoción y movimiento sin caer en clichés turísticos. Debía expresar aventura, pero también descanso; intensidad, pero también contemplación; planificación y seguridad, sin perder espontaneidad ni autenticidad. Además, la identidad debía conectar con viajeros de distintas edades y motivaciones, unidos por una misma búsqueda: vivir experiencias significativas, alejadas de los recorridos masivos y de las propuestas turísticas estandarizadas.",
        approach: [
          "Construimos la estrategia a partir de una idea central: los opuestos complementarios. En Polylepis, la aventura convive con el placer, el vértigo con la calma y la energía con la pausa.",
          "Tomamos el ciclo vital del corazón como anclaje conceptual. Sus dos movimientos —contracción y relajación— representan el ritmo natural de todo viaje: salir y regresar, avanzar y detenerse, transformarse para seguir siendo uno mismo. De esta idea surgió el círculo como símbolo del camino, el movimiento continuo y la experiencia que vuelve transformada.",
          "La identidad visual se desarrolló con una tipografía geométrica, sólida y fluida. La “o” orgánica se convirtió en el pulso del logotipo y en el principal recurso gráfico del sistema, representando el ciclo, la huella y el espacio de conciencia que deja cada recorrido. Completamos el universo con una voz cercana, serena e inspiradora, un sistema editorial flexible y una dirección visual donde el paisaje no funciona solo como destino, sino como escenario de transformación.",
        ],
        outcome: [
          "El resultado fue una marca de viajes contemporánea, distintiva y con una narrativa propia, capaz de comunicar aventura sin estridencias y profundidad sin solemnidad.",
          "Polylepis deja de presentarse únicamente como una empresa que organiza recorridos para posicionarse como una curadora de experiencias: viajes con ritmos humanos, logística cuidada y espacio para conectar con el destino y con uno mismo. El sistema visual y verbal permite construir una presencia coherente en plataformas digitales, contenidos, indumentaria, señalización, piezas editoriales y experiencias de viaje, manteniendo siempre la misma sensación de movimiento, equilibrio y autenticidad.",
        ],
        quotes: [
          "No diseñamos una marca para llegar a un destino. Diseñamos una identidad para todo lo que cambia durante el camino.",
          "Polylepis entiende el viaje como un ciclo: ir, descubrir, volver y comenzar de nuevo.",
          "Una marca donde la aventura tiene pulso y la calma también forma parte del recorrido.",
        ],
        tags: "Branding · Campaña",
        sector: "Viajes",
      },
    },
  },
  {
    slug: "punto-intimo",
    client: "Punto Íntimo",
    ...img("punto-intimo"),
    content: {
      ES: {
        title: "Sensualidad con libertad",
        tagline: "Una identidad audaz y sofisticada para una marca que invita a explorar, expresarse y disfrutar sin inhibiciones.",
        heroPhrase: "Liberá tu verdadero yo.",
        summary:
          "Rediseñamos la estrategia y la identidad visual de Punto Íntimo, una marca de prendas íntimas y accesorios que propone un espacio de exploración, confianza y autoconocimiento para las mujeres. El proyecto transforma la compra en una experiencia personal, libre de prejuicios y centrada en la autenticidad.",
        challenge:
          "Punto Íntimo necesitaba evolucionar desde una propuesta enfocada principalmente en productos hacia una marca con un propósito más amplio y emocional. El desafío era construir una identidad capaz de hablar de sensualidad, deseo e intimidad sin caer en códigos vulgares, estereotipos femeninos ni mensajes que impusieran una única manera de vivir el cuerpo. La marca debía ser provocadora pero no agresiva, sofisticada sin volverse distante y cercana sin perder carácter. También necesitaba generar un entorno de confianza donde mujeres de distintas edades, estilos y experiencias pudieran sentirse representadas, comprendidas y libres de juicios.",
        approach: [
          "Construimos el posicionamiento alrededor de un concepto central: libertad íntima. Una idea que entiende la sensualidad como una forma de expresión personal, autoconocimiento y conexión con la propia identidad.",
          "Definimos una personalidad basada en la libertad, la autenticidad, la creatividad y una sensualidad segura de sí misma. La comunicación deja de hablar únicamente sobre prendas para hablar de explorar, elegir y abrazar cada faceta personal con confianza.",
          "La identidad visual combina una estructura tipográfica contundente con un gesto inesperado: un pequeño ají integrado al logotipo, que incorpora picardía, energía y una expresión reconocible sin perder sofisticación. La paleta de rosa salmón y negro genera un contraste entre calidez y actitud, mientras que la fotografía propone una mirada íntima, honesta y cinematográfica del cuerpo. El sistema se extendió a packaging, papelería, envíos, piezas editoriales y aplicaciones comerciales, construyendo una experiencia coherente en cada punto de contacto.",
        ],
        outcome: [
          "El resultado fue una marca más segura, contemporánea y distintiva, capaz de apropiarse del territorio de la sensualidad desde una perspectiva positiva y libre de prejuicios.",
          "Punto Íntimo deja de presentarse solamente como una tienda para convertirse en un espacio de exploración personal, donde los productos, la asesoría y la experiencia de marca acompañan a cada mujer sin imponer expectativas. La nueva identidad equilibra atrevimiento y sofisticación, permitiendo que la marca se exprese con fuerza en entornos físicos, digitales y comerciales sin perder cercanía ni sensibilidad.",
        ],
        quotes: [
          "No diseñamos una marca para ocultar la intimidad. Diseñamos una identidad para vivirla con libertad.",
          "Convertimos la sensualidad en un territorio de expresión, confianza y autenticidad.",
          "Una marca que no define cómo debe sentirse una mujer: le da espacio para descubrirlo.",
        ],
        tags: "Rebranding",
        sector: "Retail",
      },
    },
  },
  {
    slug: "san-pietro",
    client: "San Pietro",
    ...img("san-pietro"),
    content: {
      ES: {
        title: "Una historia de empuje, honestidad y oficio",
        tagline: "Una identidad que convierte años de trabajo, cuidado y aprendizaje en una experiencia gastronómica que se siente antes de poder explicarse.",
        heroPhrase: "Sin palabras.",
        summary:
          "Rediseñamos la estrategia y la identidad visual de San Pietro, un restaurante nacido del trabajo compartido, la perseverancia y una manera profundamente humana de entender la gastronomía. El proyecto transformó una experiencia ya querida por sus clientes en una marca clara, consistente y preparada para expresar todo lo que sucede detrás de cada plato.",
        challenge:
          "San Pietro era un restaurante consolidado, con clientes que regresaban, una experiencia valorada y un fuerte sentido de pertenencia en torno a sus espacios. Sin embargo, esa construcción emocional no estaba traducida en una identidad clara para quienes todavía no conocían su historia. La marca era percibida principalmente como un lugar donde se comía muy bien a un precio razonable. El desafío consistía en elevar ese posicionamiento y expresar una promesa más profunda que la combinación de cocina italiana y propuesta sin gluten. También era necesario unificar dos públicos, dos sedes y dos cocinas bajo una misma narrativa, sin perder la cercanía del restaurante de barrio ni la madurez de una experiencia gastronómica más aspiracional.",
        approach: [
          "Partimos de la historia real de San Pietro y encontramos tres pilares que ya estaban presentes en su manera de trabajar: empuje, honestidad y oficio. El empuje representa la capacidad de avanzar incluso cuando el camino se vuelve difícil. La honestidad define una forma directa y humana de relacionarse con clientes y equipo, y se expresa especialmente en el cuidado con el que se desarrolló una cocina sin gluten segura e inclusiva. El oficio reúne el método, la disciplina, la escucha y la búsqueda constante de precisión.",
          "Construimos el concepto “Sin palabras” para sintetizar aquello que sucede cuando la experiencia habla por sí misma: el primer bocado, un plato que llega a la mesa, las manos que comparten, una sobremesa que se extiende o un sabor que vuelve a la memoria días después.",
          "La identidad visual combina el peso de la tradición con la calidez del hogar. Diseñamos un logotipo serif de carácter clásico, cuyo remate envolvente representa el abrazo de una mesa que recibe a todos. El sistema se completó con un monograma caligráfico, grabados históricos, sellos de origen, una paleta sobria y una composición editorial de intensidad contenida.",
        ],
        outcome: [
          "El resultado fue una marca madura, coherente y profundamente vinculada con la manera real de trabajar de San Pietro.",
          "La nueva identidad permite comunicar que el restaurante no se define únicamente por sus platos, sino por el cuidado, la precisión y la historia que existen detrás de ellos. La doble cocina deja de ser solamente una característica operativa para convertirse en una expresión concreta de responsabilidad, confianza e inclusión. San Pietro se posiciona así como una manera propia de hacer gastronomía: silenciosa, honesta y precisa, capaz de dejar una impresión duradera sin necesidad de exageraciones.",
        ],
        quotes: [
          "No inventamos una historia para San Pietro. Le dimos forma a una historia que llevaba años construyéndose en cada plato.",
          "Una identidad donde el oficio no necesita exhibirse: se percibe en cada detalle.",
          "Cuando la experiencia es verdadera, la marca puede dejar que el resultado hable por sí mismo.",
        ],
        tags: "Rebranding · Packaging",
        sector: "Restaurante",
      },
    },
  },
  {
    slug: "barbale",
    client: "Barbalé",
    ...img("barbale"),
    content: {
      ES: {
        title: "Una nueva forma de producir y exportar alimentos",
        tagline: "Una identidad que convierte trazabilidad, calidad e innovación en certezas para toda la cadena agroalimentaria.",
        heroPhrase: "Somos la iniciativa del agro.",
        summary:
          "Desarrollamos la estrategia y la identidad visual de Barbalé, una empresa agroalimentaria argentina especializada en el cultivo, procesamiento y exportación de legumbres y variedades diferenciadas. El proyecto transformó un modelo productivo integral en una marca contemporánea, confiable y preparada para conectar el origen local con mercados globales.",
        challenge:
          "Barbalé necesitaba construir una marca capaz de representar mucho más que la producción y comercialización de legumbres. El desafío consistía en expresar un modelo de negocio que controla cada etapa de la cadena de valor —desde el cultivo hasta el destino final— y traducir esa complejidad en una propuesta clara para compradores internacionales, distribuidores, productores y actores del sector agroexportador. La identidad debía transmitir rigor técnico, trazabilidad y escala global sin caer en los códigos visuales tradicionales del agro. También debía diferenciar a Barbalé en una categoría donde muchas empresas hablan de calidad, pero pocas logran demostrar una visión integral del proceso y una capacidad real para conectar productores, mercados y resultados.",
        approach: [
          "Construimos la estrategia alrededor de una idea central: Barbalé es iniciativa. La iniciativa para perfeccionar procesos, elevar estándares, garantizar la trazabilidad, explorar nuevos cultivos y desarrollar relaciones duraderas. Este concepto permitió presentar a la marca no como una empresa que espera las condiciones adecuadas, sino como una organización que toma decisiones, actúa y construye oportunidades.",
          "Definimos una personalidad resistente, integral, detallista e innovadora, acompañada por un tono preciso, profesional y cercano. La comunicación se basa en hechos, procesos y resultados comprobables, evitando promesas grandilocuentes y reforzando la confianza desde la transparencia.",
          "La identidad visual nació de una abstracción del poroto. Las formas se enlazan para representar trazabilidad, conexión y funcionamiento sistémico: cada elemento depende de los demás para que el producto avance desde su origen hasta el mercado. El símbolo se combinó con una tipografía moderna y una paleta que equilibra verdes profundos, tonos naturales y acentos contemporáneos, construyendo un sistema técnico, flexible y reconocible.",
        ],
        outcome: [
          "El resultado fue una marca agroalimentaria sólida y contemporánea, capaz de comunicar precisión técnica sin perder cercanía ni vínculo con el territorio.",
          "Barbalé deja de presentarse únicamente como productora y exportadora para posicionarse como una empresa que aporta control, transparencia y previsibilidad a toda la cadena de valor. La identidad hace visible su capacidad para integrar campo, procesamiento, logística y mercado bajo un mismo modelo de gestión. El nuevo sistema permite proyectar la marca con coherencia en documentos corporativos, muestras comerciales, packaging, plataformas digitales, ferias internacionales y aplicaciones operativas, reforzando su ambición de convertirse en un referente argentino de producción agroalimentaria de precisión.",
        ],
        quotes: [
          "No diseñamos una marca para vender legumbres. Diseñamos una identidad para conectar origen, proceso y destino.",
          "Convertimos el control de la cadena de valor en una promesa clara de calidad, trazabilidad y confianza.",
          "Barbalé no espera que el futuro del agro suceda: toma la iniciativa para construirlo.",
        ],
        tags: "Branding · Estrategia",
        sector: "Agroindustria",
      },
    },
  },
  {
    slug: "poligono-cordoba",
    client: "Polígono Córdoba",
    ...img("poligono-cordoba"),
    content: {
      ES: {
        title: "Una nueva escala industrial",
        tagline: "Una identidad que conecta desarrollo industrial, tecnología y responsabilidad ambiental para impulsar nuevas formas de producir y crecer.",
        heroPhrase: "La nueva escala industrial.",
        summary:
          "Desarrollamos la estrategia y la identidad visual de Polígono Córdoba, un parque industrial concebido para integrar infraestructura, conectividad, innovación y sustentabilidad en un mismo ecosistema empresarial. El proyecto transformó una propuesta inmobiliaria e industrial en una marca capaz de expresar una visión concreta sobre el futuro productivo de la región.",
        challenge:
          "Polígono Córdoba necesitaba presentarse como algo más que un espacio físico donde instalar empresas. El desafío consistía en construir una marca capaz de comunicar un modelo industrial contemporáneo: estratégicamente ubicado, gestionado por profesionales con experiencia y alineado con los principios de conectividad, economía circular y sustentabilidad ambiental. La identidad debía transmitir solidez y capacidad de gestión, pero también proyectar innovación y futuro. Era necesario diferenciar al proyecto de los parques industriales tradicionales, históricamente vinculados con modelos productivos aislados, poco colaborativos y de alto impacto ambiental.",
        approach: [
          "Construimos la estrategia alrededor de una idea central: Polígono Córdoba representa una nueva escala de innovación y desarrollo industrial. La escala no se entiende únicamente como crecimiento físico o económico, sino como la capacidad de generar sinergias entre empresas, incorporar tecnología, mejorar la conectividad y desarrollar prácticas productivas responsables con el ambiente.",
          "La identidad visual sintetiza esta visión mediante un símbolo que combina tres conceptos: el engranaje industrial, la circularidad de un sistema sostenible y ocho piezas vinculadas con las acciones ambientales impulsadas por el parque. El resultado es una figura abierta y dinámica, donde cada elemento mantiene su individualidad, pero forma parte de un sistema común.",
          "La paleta azul, gris oscuro y blanco refuerza la relación entre tecnología, profesionalismo y claridad, mientras que la combinación tipográfica aporta fuerza institucional y legibilidad en entornos corporativos, digitales y espaciales.",
        ],
        outcome: [
          "El resultado fue una identidad sólida, tecnológica y reconocible, capaz de posicionar a Polígono Córdoba como un ecosistema empresarial y no solamente como un parque industrial.",
          "La marca hace visible la convergencia entre infraestructura, experiencia de gestión, conectividad y sustentabilidad. También ofrece un sistema flexible para acompañar el crecimiento del proyecto en señalización, arquitectura, comunicación comercial, plataformas digitales, indumentaria y piezas institucionales. Polígono Córdoba se presenta así como un espacio preparado para empresas que buscan desarrollarse dentro de un modelo productivo más eficiente, colaborativo y alineado con el futuro de las ciudades.",
        ],
        quotes: [
          "No diseñamos una marca para ocupar un territorio. Diseñamos una identidad para transformar la manera de producir dentro de él.",
          "Convertimos industria, conectividad y sustentabilidad en un sistema visual capaz de funcionar como un verdadero ecosistema.",
          "Polígono Córdoba propone crecer en escala sin perder de vista el impacto de cada decisión.",
        ],
        tags: "Branding · Web",
        sector: "Industrial",
        location: "Córdoba",
      },
    },
  },
];

/* ---------------------------------------------------------------------------
   Accessors
--------------------------------------------------------------------------- */

export interface LocalizedProject extends ProjectContent {
  slug: string;
  client: string;
  year?: string;
  cover: string;
  coverAnimated?: string;
  gallery: string[];
  video?: string;
  index: number;
  num: string;
  total: string;
}

function pickContent(p: Project, lang: Lang): ProjectContent {
  const translated = TRANSLATIONS[p.slug]?.[lang];
  return (translated || p.content[lang] || p.content.ES || p.content.EN || Object.values(p.content)[0]) as ProjectContent;
}

export function getProjects(lang: Lang): LocalizedProject[] {
  const total = (PROJECTS.length < 10 ? "0" : "") + PROJECTS.length;
  return PROJECTS.map((p, i) => ({
    ...pickContent(p, lang),
    slug: p.slug,
    client: p.client,
    year: p.year,
    cover: p.cover,
    coverAnimated: p.coverAnimated,
    gallery: p.gallery,
    video: p.video,
    index: i,
    num: (i < 9 ? "0" : "") + (i + 1),
    total,
  }));
}

export function getProject(slug: string, lang: Lang): LocalizedProject | undefined {
  return getProjects(lang).find((p) => p.slug === slug);
}
