import type { Lang } from "./i18n";
import imageManifest from "./projects.images.json";
import projectContent from "./projects.content.json";

/* All copy for every project, in the four languages, keyed by slug. Kept in a
   single JSON (lib/projects.content.json) so the texts are easy to review and
   replace. Missing languages fall back to Spanish (the source language). */
const CONTENT = projectContent as Record<string, Partial<Record<Lang, ProjectContent>>>;

/* ---------------------------------------------------------------------------
   Project content model.

   One metadata entry per real project (below); all copy lives per-language in
   lib/projects.content.json. When a language is missing the accessor falls back
   to Spanish (the source language), so the site works in all four languages.

   Images are referenced by convention at /uploads/projects/<slug>/… and degrade
   to the striped placeholder until the real files are dropped in public/.
--------------------------------------------------------------------------- */

export interface ProjectContent {
  /** Short descriptor shown as the card/panel headline — no client name, no
      "Branding/Rebranding" (the client is always shown next to it). e.g.
      "Comunicación sin barreras" */
  title: string;
  /** "Frase descriptiva del proyecto" */
  tagline: string;
  /** Hero phrase */
  heroPhrase: string;
  /** Overview body */
  summary: string;
  /** The challenge */
  challenge: string;
  /** Our approach — one entry per paragraph */
  approach: string[];
  /** The outcome — one entry per paragraph */
  outcome: string[];
  /** "Frases sobre el proyecto" */
  quotes: string[];
  /** Discipline tags, e.g. "Branding · Estrategia" */
  tags: string;
  /** Sector, e.g. "Tecnología" */
  sector: string;
  /** City, when known */
  location?: string;
}

export interface Project {
  slug: string;
  client: string;
  year?: string;
  cover: string;
  /** Animated cover (a .gif) used ONLY on the individual project page's hero.
      The home rail and the archive keep the static `cover` image. */
  coverAnimated?: string;
  gallery: string[];
  video?: string;
  /** Desktop URL → mobile (9:16) URL, for any asset with a `-mobile` variant. */
  mobileMap?: Record<string, string>;
}

/* Images per project come from lib/projects.images.json, generated by
   scripts/build-image-manifest.mjs scanning public/uploads/projects/<slug>/.
   Drop files there with any names (see docs/ASSETS.md) — the manifest is
   rebuilt automatically before every build/dev run. Until a project has real
   files it falls back to the by-convention placeholder paths, which degrade to
   the striped placeholder. `cover` is the first image; `gallery` is the rest
   (the detail page uses the first four and shows any extras in a closing grid). */
const MANIFEST = imageManifest as Record<string, { images: string[]; hero?: string; video?: string; mobile?: Record<string, string> }>;

const img = (slug: string) => {
  const entry = MANIFEST[slug];
  const files = entry?.images ?? [];
  const coverAnimated = entry?.hero;
  const video = entry?.video;
  const mobileMap = entry?.mobile;
  if (files.length === 0) {
    return {
      cover: `/uploads/projects/${slug}/cover.webp`,
      gallery: [1, 2, 3, 4].map((n) => `/uploads/projects/${slug}/${n}.webp`),
      coverAnimated,
      video,
      mobileMap,
    };
  }
  const cover = files[0];
  const rest = files.length > 1 ? files.slice(1) : files;
  return { cover, gallery: rest, coverAnimated, video, mobileMap };
};

export const PROJECTS: Project[] = [
  { slug: "dillo", client: "Dillo", ...img("dillo") },
  { slug: "casa-capo", client: "Casa Capo", ...img("casa-capo") },
  { slug: "lomo-loco", client: "Lomo Loco", ...img("lomo-loco") },
  { slug: "polylepis", client: "Polylepis", ...img("polylepis") },
  { slug: "punto-intimo", client: "Punto Íntimo", ...img("punto-intimo") },
  { slug: "san-pietro", client: "San Pietro", ...img("san-pietro") },
  { slug: "barbale", client: "Barbalé", ...img("barbale") },
  { slug: "poligono-cordoba", client: "Polígono Córdoba", ...img("poligono-cordoba") },
];

/* ---------------------------------------------------------------------------
   Accessors
--------------------------------------------------------------------------- */

export interface LocalizedProject extends ProjectContent {
  slug: string;
  client: string;
  year?: string;
  cover: string;
  coverAnimated?: string;
  gallery: string[];
  video?: string;
  mobileMap?: Record<string, string>;
  index: number;
  num: string;
  total: string;
}

function pickContent(slug: string, lang: Lang): ProjectContent {
  const c = CONTENT[slug] || {};
  return (c[lang] || c.ES || Object.values(c)[0]) as ProjectContent;
}

export function getProjects(lang: Lang): LocalizedProject[] {
  const total = (PROJECTS.length < 10 ? "0" : "") + PROJECTS.length;
  return PROJECTS.map((p, i) => ({
    ...pickContent(p.slug, lang),
    slug: p.slug,
    client: p.client,
    year: p.year,
    cover: p.cover,
    coverAnimated: p.coverAnimated,
    gallery: p.gallery,
    video: p.video,
    mobileMap: p.mobileMap,
    index: i,
    num: (i < 9 ? "0" : "") + (i + 1),
    total,
  }));
}

export function getProject(slug: string, lang: Lang): LocalizedProject | undefined {
  return getProjects(lang).find((p) => p.slug === slug);
}
